repos:
  - repo: local
    hooks:
      - id: lint-fix
        name: npm lint fix
        entry: npm run lint:fix
        language: system
        pass_filenames: false

      - id: format-fix
        name: npm format fix
        entry: npm run format
        language: system
        pass_filenames: false

      - id: lint-check
        name: npm lint check
        entry: npm run lint:check
        language: system
        pass_filenames: false

      - id: format-check
        name: npm format check
        entry: npm run format:check
        language: system
        pass_filenames: false